version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
    open-pull-requests-limit: 20
    commit-message:
      prefix: ":arrow_up: deps"
      prefix-development: ":arrow_up: build"
      include: "scope"
    groups:
      pytest:
        dependency-type: "development"
        patterns:
          - "pytest"
          - "pytest-*"
      sphinx:
        dependency-type: "development"
        patterns:
          - "sphinx"
          - "sphinx-*"
