name: publish

permissions:
  actions: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:

  pypi:

    if: ${{ github.actor != 'dependabot[bot]' && github.ref_type == 'tag' }}

    strategy:
      matrix:
        platform:
          - ubuntu-latest
        python-version:
          - '3.12'

    runs-on: ${{ matrix.platform }}

    env:
      TAG_NAME: ${{ github.ref_name }}

    steps:

      - uses: actions/checkout@v4

      - name: Find matching release branch
        run: >
          {
            printf '%s' 'MATCHING_RELEASE_BRANCH=' ;
            git branch -r --contains ${{ env.TAG_NAME }} --format '%(refname)' |
            grep -qE '^refs/remotes/origin/(main|release-${{ env.TAG_NAME }})$' |
            head -n1 ;
          }
          >> "$GITHUB_ENV"

      - name: Abort if tag is not on release branch
        if: env.MATCHING_RELEASE_BRANCH == ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run cancel ${{ github.run_id }}
          gh run watch ${{ github.run_id }}

      - uses: ./.github/actions/set-up-poetry
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build package
        run: |
          poetry build

      - name: Wait for CI checks workflow to succeed
        uses: ArcticLampyrid/action-wait-for-workflow@v1.0.1
        with:
          workflow: ci.yml
          sha: ${{ github.sha }}

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          user: __token__
          password: ${{ env.PYPI_API_TOKEN }}
          packages-dir: dist/
